### ISSUE TITLE
[UPDATE] feature/signup

### ISSUE THREAD

**Issue by kybaq** [gather-here/gather_here#105]
## Description

로그인폼 배경색상 변경, 전체적으로 반응형 수정, 회원가입 폼 크기조절
추가로 사용하지 않는 코드 정리했습니다.

## To-Do

- [x] 로그인 폼 배경 색상 변경
- [x] 회원가입 폼 크기 조절
- [x] 담당한 부분의 반응형 디자인 수정
- [x] 미 사용 코드 정리

## ETC

누락된 이슈 대신 올렸습니다.

## up-to-date

24.08.04
