### ISSUE TITLE
[UPDATE] update/images_update

### ISSUE THREAD

**Issue by leeboa2005** [gather-here/gather_here#111]
## Description

-  로고 추가 
-  파비콘, og 이미지 추가 
-  마이페이지 로딩페이지 추가 
-  마이페이지 캐릭터 아이콘 변경

## To-Do

-   [x] 로고 추가 
-   [x] 파비콘, og 이미지 추가 
-   [x] 마이페이지 캐릭터 아이콘 변경
-   [x] 로그인 페이지 마지막 환영 이미지 변경
-   [x] 마이페이지 로딩페이지 추가 
-   [x] IT 행사 탭 내관심글 추가 
-   [x] 메인 디테일페이지 css 수정 및 로딩페이지 추가

## up-to-date
2024.08.04

**Comment by leeboa2005** [comment]
머지 완료
