### ISSUE TITLE
[STYLE] style/fix_css

### ISSUE THREAD

**Issue by leeboa2005** [gather-here/gather_here#124]
## Description

마진 수정
글작성 페이지 textarea 높이 추가 
글작성 페이지 icon 색상 디자인 시안과 동일하게 변경 
메인 이벤트 디테일 로딩페이지 추가 

## To-Do

- [X] 마진 수정
- [X] 글자 색상 추가 
- [X]  글작성 페이지 textarea 높이 추가 
- [X]  글작성 페이지 반응형 (모바일) 수정
- [X]  글작성 페이지 icon 색상 디자인 시안과 동일하게 변경 
- [X] 메인 이벤트 디테일 로딩페이지 추가 

## up-to-date
2024-08-05

**Comment by leeboa2005** [comment]
머지 완료
