### ISSUE TITLE
[FEATURE] feature/mypage_ui

### ISSUE THREAD

**Issue by leeboa2005** [gather-here/gather_here#14]
## Description

mypage 전반적인 UI 작업 

## To-Do

-   [x] 마이페이지 전체 UI 생성 
-   [x]  왼쪽 고정 메뉴바 만들기 
-   [x]  프로필 수정 UI 만들기 
-   [x]  내관심글, 내작성글 탭 만들기 
-   [x]  회원 탈퇴 모달창 UI 만들기

## up-to-date
2024.07.24

**Comment by leeboa2005** [comment]
마이페이지 (와이어프레임) UI 작업 완료

**Comment by leeboa2005** [comment]
깃 충돌로 새로운 브렌치로 변경
