### ISSUE TITLE
[FIX] fix/image_optimization_disable

### ISSUE THREAD

**Issue by kybaq** [gather-here/gather_here#148]
## Description

Next js 에서 제공하는 image optimzation 기능을 비활성화, 채팅창에서 발생하는 이미지 오류를 함께 수정.

추가로, 이슈 템플릿 수정

## To-Do

- [x] Image optimization 비활성화
- [x] 이미지 오류 수정
- [x] 이슈 템플릿 수정

## up-to-date

24.08.06
