### ISSUE TITLE
[UPDATE] feature/MainPage

### ISSUE THREAD

**Issue by LeeHareum** [gather-here/gather_here#15]
## To-Do

-   [x] 캐러셀 전체에서 빼고 스터디 / 프로젝트에만 & 각 탭에맞는 게시물 가져오기
-   [x] 마감임박 D-7일이내 게시물만 보이기
-   [x] 와이어프레임에 맞춰서 카테고리, 캐러셀카드 UI
