### ISSUE TITLE
[FEATURE] feature/posting

### ISSUE THREAD

**Issue by Eunyoung-Jo** [gather-here/gather_here#18]
## To-Do

-   [x] input, 드롭다운 
-   [x] 다중 선택 드롭다운
-   [x] quill 라이브러리로 content 받기
-   [x] supabase에 데이터 넣기

### npm install react-select
npm install react-quill
npm install quill 설치 부탁드립니다!
