### ISSUE TITLE
[UPDATE] mainPage2

### ISSUE THREAD

**Issue by LeeHareum** [gather-here/gather_here#193]
## Description

'D--1' 1일 지난 게시물 제거 (캐러셀,리스트) , ui 수정

## To-Do

- [x] 게시물 D--1 제거
- [x] 이벤트캐러셀 xs사이즈 반응형
- [x] sytle : 피그마 반영 수정
- [x] 채팅 : 최근톡이 보여지도록 채팅 내 스크롤바 최하위로 기본설정, ui

## up-to-date

08.09
