### ISSUE TITLE
[UPDATE] update/mypage_mobile_and_hover

### ISSUE THREAD

**Issue by leeboa2005** [gather-here/gather_here#199]
## Description

- 마이페이지 모바일 디자인 적용 
- 마이페이지 내작성글 호버시 수정 및 삭제 버튼 추가 
- 마이페이지 내관심글, 내작성글 S사이즈 UI 수정
- 해더 모바일 UI 수정 

## To-Do

- [x] 마이페이지 모바일 디자인 적용 
- [x] 마이페이지 내작성글 호버시 수정 및 삭제 버튼 추가 
- [x] 마이페이지 S사이즈 내관심글 내작성글 UI 수정 
- [x] 해더 모바일 UI 수정 

## ETC
**공통 컴포넌트 사용할때  크게 수정 되는 부분이 있다면 미리 공유 부탁드려요🥹**
PostCardShort 컴포넌트가 S 사이즈에서는 hidden 처리되서 
마이페이지에서 본문 내용이 안보이는 이슈가 발생하였습니다. 
지금은 Long 카드로 변경후 따로 넓이를 설정하여 사용하는 방식으로 수정하였습니다. 

- 수정 전 
![image](https://github.com/user-attachments/assets/823682cf-925e-4524-b061-5b64358516fc)
- 수정 후
![image](https://github.com/user-attachments/assets/01f636ec-5938-4a6a-a500-56a3ebeeda3c)

## up-to-date
2024.08.10
