### ISSUE TITLE
[REFACTOR] refactor/refactor_main_sidebar

### ISSUE THREAD

**Issue by kybaq** [gather-here/gather_here#200]
## Description

MainLayout 요소가 각 페이지마다 들어있어 캘린더 / 채팅이 여전히 새로 불러와지고 있어
(mainpage)/layout.tsx 내부로 위치를 변경

캘린더가 모바일 레이아웃에서 사라져서 이를 다시 추가

기존의 채팅 컴포넌트를 모달화 시켜 토글 버튼으로 켜고 끌 수 있도록 구조 변경
(현재 모바일 레이아웃에서는 이게 구현되어있으며 PC 버전에서도 적용하기 위함)

## To-Do

- [x] PC 레이아웃에서 채팅 컴포넌트 모달화
- [x] 캘린더가 모바일 레이아웃에서 다시 나타나도록 설정
- [x] MainLayout 위치 변경
- [x] 토글 버튼 디자인 시안 반영
- [x] Chat 컴포넌트 내부 동작 커스텀 훅으로 만들기

## up-to-date

24.08.10
