### ISSUE TITLE
[UPDATE] mainPage2

### ISSUE THREAD

**Issue by LeeHareum** [gather-here/gather_here#203]
## Description
게시물 유저피드백 & 자체 필요작업 부분들

## To-Do
기능 ( 일단 피드백은 다 적어봄. 의논해서 진행하면 될 듯 )
- [x] 게시물 최신글순
- [x] 캐러셀 게시물 마감일수가 적은 순서로 
- [x] 페이지 상단이동 ▶︎ 'Top버튼' , 모바일에선 없게
- [x] 캐러셀 양쪽 돌아가게 ~~~

UI
- [x] 필터바 컴포넌트_globals.css / pointer 적용
- [x] 배너_본래 사이즈가 얇은 것만 뚠뚠광고로
- [x] 필터링 후 값이 없을때 다른멘트로 ▶︎ '해당 조건에 맞는 게시물이 없습니다.'

## ETC

추가되면 적겠슴드

## up-to-date

08.13
