### ISSUE TITLE
[UPDATE] update/mypage_apply_feedback

### ISSUE THREAD

**Issue by leeboa2005** [gather-here/gather_here#207]
## Description

-  마이페이지 아이콘 누르면 나타나는 모달이 페이지 이동 시 닫힘, 백드롭 누르면 닫힘 
-  마이페이지 취소 버튼 -> 홈으로 이동, 모바일일때는 백버튼으로 변경 
-  토스트 알림 한번만 실행되게 작업하기( 기능 개선 )  

## To-Do

- [x] 마이페이지 아이콘 누르면 나타나는 모달이 페이지 이동 시 닫힘, 백드롭 누르면 닫힘 
- [x] 마이페이지 취소 버튼 기능 수정 
- [x] 마이페이지 취소 버튼 눌렀을때 컨펌 모달 생성
- [x]  Toast 알람 한번만 실행되게 작업하기, Toast  커스텀( 디자인 적용 ) -> 전체 적용 
- [x]  마이페이지 에러 수정완료
- [x]  내작성글 5개이상일때 전체 5개로 나오는 버그 수정
- [x]  내관심글 취소시 실시간 반영 
- [x]  페이지네이션 bottom 고정 (css)
- [x]  마이페이지 내정보 수정 유효성 검사 강화 

## up-to-date
2024.08.13
