### ISSUE TITLE
[STYLE] update/chat_modal

### ISSUE THREAD

**Issue by kybaq** [gather-here/gather_here#208]
## Description

채팅창이 데스크탑 / 모바일 관련 없이 모달창으로 바뀌게 되면서 디자인 시안에 맞춰 작업
추가로, 유저 테스트 피드백을 반영하기 위해 엔터 키 입력 시 채팅이 전송되도록 수정
줄 바꿈은 shift + enter 조합일 때 동작

## To-Do

- [x] 모달 닫기 아이콘 추가하기
- [x] 채팅창 모달 디자인 시안 반영
- [x] enter 키 입력 시 채팅 전송되도록 수정

## ETC

이슈 템플릿에 오타가 있어 함께 수정할 예정

## up-to-date

24.08.13
