### ISSUE TITLE
[UPDATE] feature/MainPage

### ISSUE THREAD

**Issue by LeeHareum** [gather-here/gather_here#21]
## To-Do
-   [x]  mainPage 서버컴포넌트 수정
-   [x] 게시물 리스트용카드 컴포넌트
-   [x] 전체 / 스터디 / 프로젝트탭 게시물 리스트 
-   [x] 디자인요청 : 각 카드에맞게 내용 2,3줄에 ...(말줄임)
-   [x] 무한스크롤

## ETC

...(말 줄임)구현을 위해 tailwind.config.js파일에 플러그인을 추가했으며, 아래의 패키지 설치가 필요합니다.
```js
npm install @tailwindcss/line-clamp

```
무한스크롤 하단 패키지설치
```js
npm install react-infinite-scroll-component
```
