### ISSUE TITLE
[STYLE] style/techStack

### ISSUE THREAD

**Issue by LeeHareum** [gather-here/gather_here#211]
## Description
▼ 아래의 유저피드백 반영 & 컬러버젼
기술 스택이 아이콘만 있으니 처음 보는 기술은 뭔지 이름도 모르겠음. 글이 같이 있으면 어떨지

## To-Do

- [x] 아이콘만svg+텍스트따로 vs 아이콘+텍스트svg 둘 중 선택 test 
- [x] 확정본으로 전체 스택 반영
- [x] 포스트/디테일/작성/수정 UI & 게시물상세 반응형
- [x] (게시물상세-수정하기-게시물목록돌아가기) 무한루프 버그 수정

## up-to-date

08.16
