### ISSUE TITLE
[STYLE] style/update_itevent_reactiveweb

### ISSUE THREAD

**Issue by leeboa2005** [gather-here/gather_here#218]
## Description

-  IT 이벤트 이미지 비율에 맞게 작업 
-  IT 이벤트 메인 반응형 UI 업데이트 
-  IT 이벤트 메인 디테일 반응형 UI 업데이트 

## To-Do
- [x] 이벤트페이지 이미지 비율에 맞게 작업 
- [x] 이벤트 메인 반응형 UI 업데이트 
- [x] 이벤트 메인 디테일 반응형 UI 업데이트 

## up-to-date
2024.08.18
