### ISSUE TITLE
[FEATURE] feature/mypage_ui_2

### ISSUE THREAD

**Issue by leeboa2005** [gather-here/gather_here#23]
## Description

깃 충돌 해결하여 브렌치 다시 올립니다. 
mypage 전반적인 UI 작업 완료하였습니다. 

## To-Do

-   [x] 마이페이지 전체 UI 생성 
-   [x]  왼쪽 고정 메뉴바 만들기 
-   [x]  프로필 수정 UI 만들기 
-   [x]  내관심글, 내작성글 탭 만들기 
-   [x]  회원 탈퇴 모달창 UI 만들기

## up-to-date
2024.07.24

**Comment by leeboa2005** [comment]
머지 완료
