### ISSUE TITLE
[STYLE] style/postdetail

### ISSUE THREAD

**Issue by Eunyoung-Jo** [gather-here/gather_here#245]
## Description

디자이너님 QA 디테일 작업

## To-Do

- [x] 타이틀 폰트 bold
- [x] post 마진 두기
- [x] 돌아가기 버튼 router 재설정
- [ ] 기타 수정사항들
