### ISSUE TITLE
[FEATURE] feature/gather_hub

### ISSUE THREAD

**Issue by ilovezerocokeya** [gather-here/gather_here#289]
## Description

게더허브 페이지 생성 및 카드, 모달 만들기

## To-Do

- [ ] 게더허브 페이지 ui구성
- [ ] 게더허브에 넣을 카드 ui생성
- [ ] 게더허브 카드를 클릭했을 시에 모달 띄어주기

## up-to-date

240916
