### ISSUE TITLE
[DEL]  del/Login

### ISSUE THREAD

**Issue by ilovezerocokeya** [gather-here/gather_here#297]
## Description

깃허브로그인 삭제.,,,

## To-Do

- [ ] 깃허브 로그인 삭제,,,
- [ ] 구글 로그인 오타 수정
- [ ] signup01 비율 수정

## up-to-date

240916
