### ISSUE TITLE
[FEATURE] feature/mainpage_IT_Events

### ISSUE THREAD

**Issue by kybaq** [gather-here/gather_here#31]
## Description

mainpage 내의 IT 행사 탭 작업을 위한 이슈입니다.

## To-Do

-   [x] IT 행사 탭 구현(게시글 불러오기)
-   [x] 카테고리 필터 추가
- [x] 좋아요 컴포넌트 추가

## up-to-date

2024-08-04
