### ISSUE TITLE
[REFACTOR] refactor/mainPage

### ISSUE THREAD

**Issue by ilovezerocokeya** [gather-here/gather_here#327]
## Description

메인페이지의 무한스크롤 라이브러리를 걷어내고 tanstackQuery -> 무한스크롤 -> 스크롤 위치 기억하기를 적용

## To-Do

- [ ] 기존의 무한스크롤관련 라이브러리 걷어내기
- [ ] 메인페이지 (all + 이벤트 + 프로젝트 + 스터디)에 tanstackQeury 적용
- [ ] 메인페이지에 무한스크롤 적용
- [ ] 스크롤 위치 기억하기까지 적용

## up-to-date

240928
