### ISSUE TITLE
[FIX]  fix/mypage_profilepicture

### ISSUE THREAD

**Issue by leeboa2005** [gather-here/gather_here#41]
## Description
프로필 아이콘 클릭시 이미지 안나오는 부분 수정하였습니다. ( 상대경로 -> 절대경로) 수정 
왼쪽 네비게이션 사용자 정보 부분 작업하였습니다. 

## To-Do
-   [x] 프로필 아이콘 클릭시 이미지 안나오는 부분 수정 완료 
-   [x] 이미지 objectFit 관련 주의 부분 수정 완료   
-   [x] 마이페이지 왼쪽 네비게이션 사용자 정보 부분 작업 완료 
-   [x] 마이페이지 왼쪽 네비게이션 스켈레톤 추가 

## up-to-date
2024.07.27

**Comment by leeboa2005** [comment]
머지 완료
