### ISSUE TITLE
[UPDATE] feature/MainPage2

### ISSUE THREAD

**Issue by LeeHareum** [gather-here/gather_here#42]
## To-Do

-   [x] 버그, 병합 후 에러 ( 스크롤내려야 캐러셀게시물등장, 게시물 중복, D-day게시물 적용 ), post타입에러
-   [x] 지난게시물 제외
-   [x] 각 페이지 캘린더 자리잡아주고
-   [x] 반응형 ( 캘린더 합친 후 각 너비에따라 게시물크기 )

#### 24.07.28
