### ISSUE TITLE
[FEATURE]  feature/create_common_area

### ISSUE THREAD

**Issue by leeboa2005** [gather-here/gather_here#45]
## Description

1. 공통으로 사용할 컬러 지정 완료
2. 폰트 설정 완료
3. 공통 컴포넌트 생성 (input, button) 완료
4. 해더 모바일 검색창 UI 작업 완료

## To-Do

- [x] 공통으로 사용할 컬러 지정 
- [x] 폰트 설정 
- [x] 공통 컴포넌트 생성 (input, button, label)
- [x] 해더 모바일 검색창 UI 작업 완료
- [x] CSS 가이드 작성

## ETC
CSS 가이드는 이슈 상단에 고정했습니다
작업전에 꼭 한번 읽어주세요! 감사합니다. 

## up-to-date
2024.07.29

**Comment by leeboa2005** [comment]
css 작성 가이드 완료
