### ISSUE TITLE
[UPDATE] mypage_connect_login

### ISSUE THREAD

**Issue by leeboa2005** [gather-here/gather_here#56]
## Description

마이페이지 프로필 수정 로그인 기능 연동 

## To-Do

-   [x] 마이페이지 프로필 수정 로그인 연동
-   [x] 마이페이지 회원 정보 수정 로그인 연동
-   [x] 왼쪽  네비게이션 로그인 연동
-   [x] 왼쪽  네비게이션 이미지 변경 수정하면 실시간으로 보이게 수정 
-   [ ] 마이페이지 회원 탈퇴 기능 구현 (모든 작업 완료하면 다시 진행하겠습니다 🥹)
-   [x] 프로필 수정 디자인 적용 
-   [x] 프로필 수정 유효성 검사 (이메일, 닉네임) 추가

## up-to-date
2024.07.31

**Comment by leeboa2005** [comment]
탈퇴 기능 제외하고 완료 (mvp 이후 진행 가능성 높음 ㅠㅠ )
