### ISSUE TITLE
[UPDATE] feature/chat_user_linkage

### ISSUE THREAD

**Issue by kybaq** [gather-here/gather_here#59]
## Description

기존 채팅 기능에서 로그인 한 유저 정보를 연동해 기능을 추가하기 위한 브랜치입니다.

## To-Do

-  [x] 로그인한 유저 정보 연동
-  [x] 비 로그인 시 채팅 입력창 비활성화
-  [x] 본인이 보낸 메시지일 때와 아닌 메시지를 구분하기
-  [x] 보낸 시간 추가

## up-to-date

2024-07-31

**Comment by leeboa2005** [comment]
완료되어서 닫아요~!
