### ISSUE TITLE
[UPDATE] update/header_mypage_update

### ISSUE THREAD

**Issue by leeboa2005** [gather-here/gather_here#64]
## Description

header 글작성 버튼 모든 뷰포트에서 보이게하기 
header 사용자 프로필, 정보 연동 
마이페이지 왼쪽 네이비게이션 수정 

## To-Do

-   [x] header 글작성 버튼 모든 뷰포트에서 보이게하기 
-   [x] header 사용자 프로필, 정보 연동 
-   [x] 마이페이지 왼쪽 네이비게이션 수정
-   [x] 모달 색상 변경

## up-to-date
2024-08-01

**Comment by leeboa2005** [comment]
머지 완료
