### ISSUE TITLE
[REFACTOR] faeture/MainPage2

### ISSUE THREAD

**Issue by LeeHareum** [gather-here/gather_here#65]
## To-Do

-   [x] 캐러셀카드 변경, 반응형 3-3-1로, 직군 한개이상은 +n 으로 표시, 리스트카드는 | 로 구분
-   [x] 필터 전체 너비로, 양쪽패딩 맞춰서 & 반응형_2개씩 위 아래로, 피그마에 맞춰서 디자인 변경
-   [x] 광고배너 radius 
-   [x] 게시물 에디터태그 제거 
-   [x] 게시물 유저프로필사진 전역상태 반영

#### 08.02

**Comment by leeboa2005** [comment]
완료되어서 닫아요~!
