### ISSUE TITLE
[FEATURE] feature/mypage_myposts

### ISSUE THREAD

**Issue by leeboa2005** [gather-here/gather_here#68]
## Description

마이페이지 글작성 페이지 작업 

## To-Do

- [x] 마이페이지 post 불러오기 
- [x] 카드 UI 적용하기  
- [x] 카테고리 별로 분류하기 
- [x]  디자인 시안 반영하기 
- [x]  스켈레톤 UI 추가

### 작업이 완료 예정인 시점을 적어주세요
2024-08-02

**Comment by leeboa2005** [comment]
작업 완료
