### ISSUE TITLE
[FEATURE] feature/MainPage

### ISSUE THREAD

**Issue by LeeHareum** [gather-here/gather_here#7]
## To-Do

-   [x] MainPage- All / Studies / Projects / Events 탭분류, 페이지 전환
-   [x] supabase Post테이블 연결 
-   [x] 게시물 카드 컴포넌트 틀( 캐러셀용 ) 
-   [x] 페이지 상단 캐러셀 

#### 캐러셀 구현시 라이브러리 패키지 설치가 필요합니다.
````js
npm install swiper
````
