### ISSUE TITLE
[FEATURE] feature/calender

### ISSUE THREAD

**Issue by kybaq** [gather-here/gather_here#8]
## Description

FullCalender API 연동 작업을 위한 issue

## To-Do

-  [x] FullCalender API 연동 후 월력 형
-  [x] 캘린더 리스트형 변환 가능하도록
-  [x] 모바일 사이즈 대응
 
## ETC

FullCalender API dependency 를 새로 설치할 예정입니다.

## up-to-date

24.07.23
