### ISSUE TITLE
[FEATURE] feature/create_header_footer

### ISSUE THREAD

**Issue by leeboa2005** [gather-here/gather_here#9]
## Description

해더 UI 작업 진행 하겠습니다.  

## To-Do

-   [X] 해더 UI 작업 (모바일 제외하고 완료) 
-   [X] 해더 로그인 전,후 임시 작업 
-   [X] 메타 태그 기본 정보 작성  

## ETC

로고, 아이콘, 전체 넓이, 모바일 디자인등 정해지면 추후 디테일한 부분 작업하겠습니다. 
푸터는 무한스크롤 페이지가 많아 없어지고, 추후에 다른 방법으로 추가할 예정입니다. (보류) 

## up-to-date

2024.07.22

**Comment by leeboa2005** [comment]
해더 UI (모바일 제외) 작업 완료
