### ISSUE TITLE
[BUG] feature/MainPage2

### ISSUE THREAD

**Issue by LeeHareum** [gather-here/gather_here#90]
## To-Do

-   [x] 스터디 / 프로젝트 하단 게시물 리스트
-   [x] 당일 게시물 포함해서 불러오기 / 당일 게시물은 d-day로 표시 
-   [x] 필터 선택 후 다시 비활성화시 게시물 초기화 / 기간 이내 | 이상 조건부
