### ISSUE TITLE
[STYLE] style/detailpage

### ISSUE THREAD

**Issue by Eunyoung-Jo** [gather-here/gather_here#91]
## To-Do

- [x] 공고글 디테일 페이지 css 작업
- [x] 행사글 디테일 페이지 css 작업
- [x] 공고글 작성 페이지 css 작업
- [x] 공고글 수정 페이지 css 작업
