### ISSUE TITLE
[FEATURE] feature/it_event_ui 

### ISSUE THREAD

**Issue by leeboa2005** [gather-here/gather_here#95]
## Description

IT 행사 UI 만들기

## To-Do

- [x] IT 행사 카드 컴포넌트 생성
- [x] IT 행사 슬라이드 카드 디자인 시안 반영 
- [x] IT 행사 리스트 카드 디자인 시안 반영 
- [x] 스크롤바 커스텀

## up-to-date
2023.08.04
